#!/bin/bash
if [ $1 -gt 100 ]; then
  echo "Please provide a value less than 100"
fi
let x=($1 * 1000)
echo -n "Setting brightness to: "
echo $x | sudo tee /sys/class/backlight/intel_backlight/brightness
