#!/bin/bash
revert() {
  rm /tmp/*screen*.png
}
trap revert HUP INT TERM
import -window root /tmp/locking_screen.png
convert -blur 0x8 /tmp/locking_screen.png /tmp/screen_blur.png
convert -composite /tmp/screen_blur.png ~/Pictures/ah-ah-ah.png -gravity Center -geometry -0x400 /tmp/screen.png
i3lock -i /tmp/screen.png
revert
