#!/bin/bash
xrandr --output DP-2-1-8 --auto --above eDP-1 --primary
xrandr --output DP-1 --auto --right-of DP-2-1-8
xrandr --output eDP-1 --pos 1700x1440
# xrandr --output DP-1-1-8 --auto --right-of eDP-1
# xrandr --output DP-2-2 --auto --right-of DP-1-1-8
# xrandr --output DP-1-1-1 --auto --right-of DP-1-1-8
# xrandr --output DP-2-1-8 --auto --right-of eDP-1
# xrandr --output DP-2-1-1 --auto --right-of DP-2-1-8
# xrandr --output DP-1-2 --auto --right-of DP-2-1-8

if [ $(xrandr |ag "DP-1-1-8 connected" | wc -l) ]; then
  xrandr --output DP-1-1-8 --primary
fi

if [ $(xrandr |ag "DP-2-1-8 connected" | wc -l) ]; then
  xrandr --output DP-2-1-8 --primary
fi
"$HOME/.fehbg"

